### ISSUE TITLE
Unuseful UndeclaredThrowableExceptions

### ISSUE THREAD

**Issue by benhamidene** [testIT-WebTester/webtester-core#7]
During the identification of elements on pages Selenium throws some time UndeclaredThrowableExceptions.

This results in very long StackTraces and unneeded scrolling activities ;)

It would be nice oif WebTester could extract the real causes behind them and give and throw it instead of the UndeclaredThrowables

**Comment by slu-it** [comment]
I've got a branch with some fixes in that direction im currently working on.

**Comment by slu-it** [comment]
With v0.9.9 most of the critical paths were an UndeclaredThrowableException was thrown were fixed by providing useful Exceptions with Detailed information on where exactly the Error occurred (i.e. The field of which class could not be initialized and why).
One of the commits in PR #9  handles all other occurrences of UndeclaredThrowableException except one where there is a good reason for having it.
